const J = (pkg, file) => 'https://cdn.jsdelivr.net/npm/' + pkg + '/' + file
const U = (pkg, file) => 'https://unpkg.com/' + pkg + '/' + file

function item(id, name, cat, css, js) {
  return { id, name, cat, css: css || '', js: js || '' }
}

export const CATALOG = [
  item('tailwind', 'Tailwind CSS', 'css', '', 'https://cdn.tailwindcss.com'),
  item('tailwind2', 'Tailwind CSS 2 (estático)', 'css', J('tailwindcss@2.2.19', 'dist/tailwind.min.css'), ''),
  item('bootstrap', 'Bootstrap 5', 'css', J('bootstrap@5.3.3', 'dist/css/bootstrap.min.css'), J('bootstrap@5.3.3', 'dist/js/bootstrap.bundle.min.js')),
  item('bootswatch-darkly', 'Bootswatch Darkly', 'css', J('bootswatch@5.3.3', 'dist/darkly/bootstrap.min.css'), ''),
  item('pico', 'Pico CSS', 'css', J('@picocss/pico@2', 'css/pico.min.css'), ''),
  item('bulma', 'Bulma', 'css', J('bulma', 'css/bulma.min.css'), ''),
  item('animatecss', 'Animate.css', 'css', J('animate.css', 'animate.min.css'), ''),
  item('normalize', 'Normalize.css', 'css', J('normalize.css', 'normalize.css'), ''),
  item('water', 'Water.css dark', 'css', J('water.css', 'out/dark.min.css'), ''),
  item('milligram', 'Milligram', 'css', J('milligram', 'dist/milligram.min.css'), ''),
  item('skeleton', 'Skeleton', 'css', 'https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css', ''),
  item('tachyons', 'Tachyons', 'css', J('tachyons', 'css/tachyons.min.css'), ''),
  item('uikit', 'UIkit', 'css', J('uikit', 'dist/css/uikit.min.css'), J('uikit', 'dist/js/uikit.min.js')),
  item('materialize', 'Materialize', 'css', J('materialize-css', 'dist/css/materialize.min.css'), J('materialize-css', 'dist/js/materialize.min.js')),
  item('foundation', 'Foundation', 'css', J('foundation-sites', 'dist/css/foundation.min.css'), J('foundation-sites', 'dist/js/foundation.min.js')),
  item('semantic', 'Semantic UI', 'css', J('semantic-ui-css', 'semantic.min.css'), J('semantic-ui-css', 'semantic.min.js')),
  item('openprops', 'Open Props', 'css', J('open-props', 'open-props.min.css'), ''),
  item('openprops-normalize', 'Open Props Normalize', 'css', J('open-props', 'normalize.min.css'), ''),
  item('modern-normalize', 'modern-normalize', 'css', J('modern-normalize', 'modern-normalize.css'), ''),
  item('marx', 'Marx', 'css', J('marx-css', 'css/marx.min.css'), ''),
  item('sakura', 'Sakura', 'css', J('sakura.css', 'css/sakura.css'), ''),
  item('newcss', 'new.css', 'css', J('@exampledev/new.css', 'new.css'), ''),
  item('mvp', 'MVP.css', 'css', J('mvp.css', 'mvp.css'), ''),
  item('chota', 'Chota', 'css', J('chota', 'dist/chota.min.css'), ''),
  item('wing', 'Wing', 'css', J('wingcss', 'dist/wing.min.css'), ''),
  item('minicss', 'mini.css', 'css', J('mini.css', 'dist/mini-default.min.css'), ''),
  item('paper', 'PaperCSS', 'css', J('papercss', 'dist/paper.min.css'), ''),
  item('nes', 'NES.css', 'css', J('nes.css', 'css/nes.min.css'), ''),
  item('98css', '98.css', 'css', J('98.css', 'dist/98.css'), ''),
  item('7css', '7.css', 'css', J('7.css', 'dist/7.css'), ''),
  item('fontawesome', 'Font Awesome 6', 'icons', J('@fortawesome/fontawesome-free', 'css/all.min.css'), ''),
  item('bootstrap-icons', 'Bootstrap Icons', 'icons', J('bootstrap-icons', 'font/bootstrap-icons.min.css'), ''),
  item('remixicon', 'Remix Icon', 'icons', J('remixicon', 'fonts/remixicon.css'), ''),
  item('lucide', 'Lucide', 'icons', '', J('lucide', 'dist/umd/lucide.min.js')),
  item('feather', 'Feather Icons', 'icons', '', J('feather-icons', 'dist/feather.min.js')),
  item('ionicons', 'Ionicons', 'icons', '', J('ionicons', 'dist/ionicons/ionicons.js')),
  item('material-icons', 'Material Icons', 'icons', 'https://fonts.googleapis.com/icon?family=Material+Icons', ''),
  item('tabler-icons', 'Tabler Icons', 'icons', J('@tabler/icons-webfont', 'tabler-icons.min.css'), ''),
  item('simple-icons', 'Simple Icons', 'icons', '', ''),
  item('flag-icons', 'Flag Icons', 'icons', J('flag-icons', 'css/flag-icons.min.css'), ''),
  item('line-awesome', 'Line Awesome', 'icons', J('line-awesome', 'dist/line-awesome/css/line-awesome.min.css'), ''),
  item('boxicons', 'Boxicons', 'icons', J('boxicons', 'css/boxicons.min.css'), ''),
  item('css.gg', 'css.gg', 'icons', J('css.gg', 'icons/all.css'), ''),
  item('inter', 'Inter', 'fonts', 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap', ''),
  item('ibm-plex', 'IBM Plex', 'fonts', 'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;600&family=IBM+Plex+Mono:wght@400;500&display=swap', ''),
  item('roboto', 'Roboto', 'fonts', 'https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap', ''),
  item('source-sans', 'Source Sans 3', 'fonts', 'https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@400;600;700&display=swap', ''),
  item('newsreader', 'Newsreader', 'fonts', 'https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,500;6..72,600&display=swap', ''),
  item('jetbrains-mono', 'JetBrains Mono', 'fonts', 'https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500&display=swap', ''),
  item('fira-code', 'Fira Code', 'fonts', 'https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;500&display=swap', ''),
  item('playfair', 'Playfair Display', 'fonts', 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;700&display=swap', ''),
  item('space-grotesk', 'Space Grotesk', 'fonts', 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;700&display=swap', ''),
  item('jquery', 'jQuery', 'js', '', J('jquery', 'dist/jquery.min.js')),
  item('jquery-ui', 'jQuery UI', 'ui', J('jquery-ui', 'dist/themes/base/jquery-ui.min.css'), J('jquery-ui', 'dist/jquery-ui.min.js')),
  item('alpine', 'Alpine.js', 'js', '', J('alpinejs', 'dist/cdn.min.js')),
  item('htmx', 'htmx', 'js', '', J('htmx.org', 'dist/htmx.min.js')),
  item('lodash', 'Lodash', 'js', '', J('lodash', 'lodash.min.js')),
  item('dayjs', 'Day.js', 'js', '', J('dayjs', 'dayjs.min.js')),
  item('luxon', 'Luxon', 'js', '', J('luxon', 'build/global/luxon.min.js')),
  item('axios', 'Axios', 'js', '', J('axios', 'dist/axios.min.js')),
  item('marked', 'Marked', 'editor', '', J('marked', 'marked.min.js')),
  item('dompurify', 'DOMPurify', 'js', '', J('dompurify', 'dist/purify.min.js')),
  item('highlight', 'Highlight.js', 'editor', J('@highlightjs/cdn-assets', 'styles/github-dark.min.css'), J('@highlightjs/cdn-assets', 'highlight.min.js')),
  item('prism', 'Prism.js', 'editor', J('prismjs', 'themes/prism-tomorrow.min.css'), J('prismjs', 'prism.min.js')),
  item('mermaid', 'Mermaid', 'charts', '', J('mermaid', 'dist/mermaid.min.js')),
  item('katex', 'KaTeX', 'editor', J('katex', 'dist/katex.min.css'), J('katex', 'dist/katex.min.js')),
  item('mathjax', 'MathJax', 'editor', '', 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'),
  item('three', 'Three.js', 'js', '', J('three', 'build/three.min.js')),
  item('anime', 'Anime.js', 'js', '', J('animejs', 'lib/anime.min.js')),
  item('gsap', 'GSAP', 'js', '', J('gsap', 'dist/gsap.min.js')),
  item('lottie', 'Lottie', 'js', '', J('lottie-web', 'build/player/lottie.min.js')),
  item('typed', 'Typed.js', 'js', '', J('typed.js', 'dist/typed.umd.js')),
  item('swiper', 'Swiper', 'ui', J('swiper', 'swiper-bundle.min.css'), J('swiper', 'swiper-bundle.min.js')),
  item('splide', 'Splide', 'ui', J('@splidejs/splide', 'dist/css/splide.min.css'), J('@splidejs/splide', 'dist/js/splide.min.js')),
  item('aos', 'AOS', 'js', J('aos', 'dist/aos.css'), J('aos', 'dist/aos.js')),
  item('scrollreveal', 'ScrollReveal', 'js', '', J('scrollreveal', 'dist/scrollreveal.min.js')),
  item('tippy', 'Tippy.js', 'ui', J('tippy.js', 'dist/tippy.css'), J('@popperjs/core', 'dist/umd/popper.min.js')),
  item('popper', 'Popper', 'js', '', J('@popperjs/core', 'dist/umd/popper.min.js')),
  item('sortablejs', 'SortableJS', 'ui', '', J('sortablejs', 'Sortable.min.js')),
  item('clipboard', 'Clipboard.js', 'js', '', J('clipboard', 'dist/clipboard.min.js')),
  item('filepond', 'FilePond', 'ui', J('filepond', 'dist/filepond.min.css'), J('filepond', 'dist/filepond.min.js')),
  item('dropzone', 'Dropzone', 'ui', J('dropzone', 'dist/dropzone.css'), J('dropzone', 'dist/dropzone-min.js')),
  item('tom-select', 'Tom Select', 'ui', J('tom-select', 'dist/css/tom-select.default.min.css'), J('tom-select', 'dist/js/tom-select.complete.min.js')),
  item('choices', 'Choices.js', 'ui', J('choices.js', 'public/assets/styles/choices.min.css'), J('choices.js', 'public/assets/scripts/choices.min.js')),
  item('flatpickr', 'flatpickr', 'ui', J('flatpickr', 'dist/flatpickr.min.css'), J('flatpickr', 'dist/flatpickr.min.js')),
  item('nouislider', 'noUiSlider', 'ui', J('nouislider', 'dist/nouislider.min.css'), J('nouislider', 'dist/nouislider.min.js')),
  item('cropper', 'Cropper.js', 'ui', J('cropperjs', 'dist/cropper.min.css'), J('cropperjs', 'dist/cropper.min.js')),
  item('photoswipe', 'PhotoSwipe', 'ui', J('photoswipe', 'dist/photoswipe.css'), J('photoswipe', 'dist/umd/photoswipe.umd.min.js')),
  item('qrcode', 'QRCode', 'js', '', J('qrcode', 'build/qrcode.min.js')),
  item('jsbarcode', 'JsBarcode', 'js', '', J('jsbarcode', 'dist/JsBarcode.all.min.js')),
  item('papaparse', 'Papa Parse', 'data', '', J('papaparse', 'papaparse.min.js')),
  item('xlsx', 'SheetJS', 'data', '', J('xlsx', 'dist/xlsx.full.min.js')),
  item('jszip', 'JSZip', 'data', '', J('jszip', 'dist/jszip.min.js')),
  item('filesaver', 'FileSaver', 'js', '', J('file-saver', 'dist/FileSaver.min.js')),
  item('html2canvas', 'html2canvas', 'js', '', J('html2canvas', 'dist/html2canvas.min.js')),
  item('jspdf', 'jsPDF', 'js', '', J('jspdf', 'dist/jspdf.umd.min.js')),
  item('codemirror', 'CodeMirror', 'editor', J('codemirror', 'lib/codemirror.css'), J('codemirror', 'lib/codemirror.js')),
  item('monaco', 'Monaco Loader', 'editor', '', J('monaco-editor', 'min/vs/loader.js')),
  item('ace', 'Ace Editor', 'editor', '', J('ace-builds', 'src-min-noconflict/ace.js')),
  item('split', 'Split.js', 'ui', '', J('split.js', 'dist/split.min.js')),
  item('nprogress', 'NProgress', 'ui', J('nprogress', 'nprogress.css'), J('nprogress', 'nprogress.js')),
  item('notyf', 'Notyf', 'ui', J('notyf', 'notyf.min.css'), J('notyf', 'notyf.min.js')),
  item('sweetalert2', 'SweetAlert2', 'ui', J('sweetalert2', 'dist/sweetalert2.min.css'), J('sweetalert2', 'dist/sweetalert2.all.min.js')),
  item('toastify', 'Toastify', 'ui', J('toastify-js', 'src/toastify.css'), J('toastify-js', 'src/toastify.js')),
  item('driver', 'Driver.js', 'ui', J('driver.js', 'dist/driver.css'), J('driver.js', 'dist/driver.js.iife.js')),
  item('introjs', 'Intro.js', 'ui', J('intro.js', 'minified/introjs.min.css'), J('intro.js', 'minified/intro.min.js')),
  item('countup', 'CountUp', 'js', '', J('countup.js', 'dist/countUp.umd.js')),
  item('progressbar', 'ProgressBar.js', 'js', '', J('progressbar.js', 'dist/progressbar.min.js')),
  item('particles', 'particles.js', 'js', '', J('particles.js', 'particles.min.js')),
  item('tsparticles', 'tsParticles', 'js', '', J('tsparticles', 'tsparticles.bundle.min.js')),
  item('p5', 'p5.js', 'js', '', J('p5', 'lib/p5.min.js')),
  item('matter', 'Matter.js', 'js', '', J('matter-js', 'build/matter.min.js')),
  item('pixi', 'PixiJS', 'js', '', J('pixi.js', 'dist/pixi.min.js')),
  item('howler', 'Howler', 'js', '', J('howler', 'dist/howler.min.js')),
  item('localforage', 'localForage', 'js', '', J('localforage', 'dist/localforage.min.js')),
  item('mustache', 'Mustache', 'js', '', J('mustache', 'mustache.min.js')),
  item('handlebars', 'Handlebars', 'js', '', J('handlebars', 'dist/handlebars.min.js')),
  item('lit', 'Lit', 'js', '', J('lit', 'index.js')),
  item('vue', 'Vue 3', 'js', '', J('vue', 'dist/vue.global.prod.js')),
  item('react', 'React', 'js', '', J('react', 'umd/react.production.min.js')),
  item('react-dom', 'ReactDOM', 'js', '', J('react-dom', 'umd/react-dom.production.min.js')),
  item('preact', 'Preact', 'js', '', J('preact', 'dist/preact.min.js')),
  item('rxjs', 'RxJS', 'js', '', J('rxjs', 'dist/bundles/rxjs.umd.min.js')),
  item('socketio', 'Socket.IO client', 'js', '', J('socket.io-client', 'dist/socket.io.min.js')),
  item('fuse', 'Fuse.js', 'data', '', J('fuse.js', 'dist/fuse.min.js')),
  item('lunr', 'Lunr', 'data', '', J('lunr', 'lunr.min.js')),
  item('minisearch', 'MiniSearch', 'data', '', J('minisearch', 'dist/umd/index.min.js')),
  item('i18next', 'i18next', 'js', '', J('i18next', 'i18next.min.js')),
  item('validator', 'validator.js', 'js', '', J('validator', 'validator.min.js')),
  item('mathjs', 'math.js', 'data', '', J('mathjs', 'lib/browser/math.js')),
  item('numeral', 'Numeral', 'data', '', J('numeral', 'min/numeral.min.js')),
  item('decimal', 'Decimal.js', 'data', '', J('decimal.js', 'decimal.min.js')),
  item('bignumber', 'BigNumber.js', 'data', '', J('bignumber.js', 'bignumber.min.js')),
  item('chartjs', 'Chart.js', 'charts', '', J('chart.js', 'dist/chart.umd.min.js')),
  item('apexcharts', 'ApexCharts', 'charts', J('apexcharts', 'dist/apexcharts.css'), J('apexcharts', 'dist/apexcharts.min.js')),
  item('echarts', 'Apache ECharts', 'charts', '', J('echarts', 'dist/echarts.min.js')),
  item('plotly', 'Plotly.js', 'charts', '', 'https://cdn.plot.ly/plotly-2.35.2.min.js'),
  item('highcharts', 'Highcharts', 'charts', '', 'https://code.highcharts.com/highcharts.js'),
  item('d3', 'D3.js', 'charts', '', J('d3', 'dist/d3.min.js')),
  item('c3', 'C3.js', 'charts', J('c3', 'c3.min.css'), J('c3', 'c3.min.js')),
  item('billboard', 'Billboard.js', 'charts', J('billboard.js', 'dist/billboard.min.css'), J('billboard.js', 'dist/billboard.pkgd.min.js')),
  item('uplot', 'uPlot', 'charts', J('uplot', 'dist/uPlot.min.css'), J('uplot', 'dist/uPlot.iife.min.js')),
  item('lightweight-charts', 'TradingView Lightweight Charts', 'market', '', J('lightweight-charts', 'dist/lightweight-charts.standalone.production.js')),
  item('amcharts', 'amCharts 5 index', 'charts', '', J('@amcharts/amcharts5', 'index.js')),
  item('vis-network', 'vis-network', 'charts', J('vis-network', 'styles/vis-network.min.css'), J('vis-network', 'standalone/umd/vis-network.min.js')),
  item('vis-timeline', 'vis-timeline', 'charts', J('vis-timeline', 'styles/vis-timeline-graph2d.min.css'), J('vis-timeline', 'standalone/umd/vis-timeline-graph2d.min.js')),
  item('cytoscape', 'Cytoscape.js', 'charts', '', J('cytoscape', 'dist/cytoscape.min.js')),
  item('leaflet', 'Leaflet', 'maps', J('leaflet', 'dist/leaflet.css'), J('leaflet', 'dist/leaflet.js')),
  item('maplibre', 'MapLibre GL', 'maps', J('maplibre-gl', 'dist/maplibre-gl.css'), J('maplibre-gl', 'dist/maplibre-gl.js')),
  item('openlayers', 'OpenLayers', 'maps', J('ol', 'ol.css'), J('ol', 'dist/ol.js')),
  item('mapbox', 'Mapbox GL', 'maps', J('mapbox-gl', 'dist/mapbox-gl.css'), J('mapbox-gl', 'dist/mapbox-gl.js')),
  item('heatmap', 'heatmap.js', 'charts', '', J('heatmap.js', 'build/heatmap.min.js')),
  item('ag-grid', 'AG Grid Community', 'tables', J('ag-grid-community', 'styles/ag-grid.css'), J('ag-grid-community', 'dist/ag-grid-community.min.js')),
  item('tabulator', 'Tabulator', 'tables', J('tabulator-tables', 'dist/css/tabulator.min.css'), J('tabulator-tables', 'dist/js/tabulator.min.js')),
  item('gridjs', 'Grid.js', 'tables', J('gridjs', 'dist/theme/mermaid.min.css'), J('gridjs', 'dist/gridjs.umd.js')),
  item('simple-datatables', 'Simple-DataTables', 'tables', J('simple-datatables', 'dist/style.css'), J('simple-datatables', 'dist/umd/simple-datatables.js')),
  item('listjs', 'List.js', 'tables', '', J('list.js', 'dist/list.min.js')),
  item('datatables', 'DataTables', 'tables', J('datatables.net-dt', 'css/dataTables.dataTables.min.css'), J('datatables.net', 'js/dataTables.min.js')),
  item('handsontable', 'Handsontable', 'tables', J('handsontable', 'dist/handsontable.full.min.css'), J('handsontable', 'dist/handsontable.full.min.js')),
  item('clusterize', 'Clusterize.js', 'tables', J('clusterize.js', 'clusterize.css'), J('clusterize.js', 'clusterize.min.js')),
  item('finance', 'Finance.js', 'market', '', J('financejs', 'finance.js')),
  item('trading-vue', 'deprecated skip', 'market', '', ''),
  item('winbox', 'WinBox', 'ui', J('winbox', 'dist/css/winbox.min.css'), J('winbox', 'dist/js/winbox.min.js')),
  item('shepherd', 'Shepherd', 'ui', J('shepherd.js', 'dist/css/shepherd.css'), J('shepherd.js', 'dist/js/shepherd.min.js')),
  item('hotkeys', 'hotkeys-js', 'js', '', J('hotkeys-js', 'dist/hotkeys.min.js')),
  item('hammer', 'Hammer.js', 'js', '', J('hammerjs', 'hammer.min.js')),
  item('interact', 'Interact.js', 'ui', '', J('interactjs', 'dist/interact.min.js')),
  item('gridstack', 'GridStack', 'ui', J('gridstack', 'dist/gridstack.min.css'), J('gridstack', 'dist/gridstack-all.js')),
  item('fullcalendar', 'FullCalendar', 'ui', J('fullcalendar', 'index.global.min.js'), J('fullcalendar', 'index.global.min.js')),
  item('toastui-editor', 'TOAST UI Editor', 'editor', J('@toast-ui/editor', 'dist/toastui-editor.min.css'), J('@toast-ui/editor', 'dist/toastui-editor-all.min.js')),
  item('toastui-chart', 'TOAST UI Chart', 'charts', J('@toast-ui/chart', 'dist/toastui-chart.min.css'), J('@toast-ui/chart', 'dist/toastui-chart.min.js')),
  item('quill', 'Quill', 'editor', J('quill', 'dist/quill.snow.css'), J('quill', 'dist/quill.js')),
  item('tinymce', 'TinyMCE', 'editor', '', J('tinymce', 'tinymce.min.js')),
  item('trix', 'Trix', 'editor', J('trix', 'dist/trix.css'), J('trix', 'dist/trix.umd.min.js')),
  item('easy-mde', 'EasyMDE', 'editor', J('easymde', 'dist/easymde.min.css'), J('easymde', 'dist/easymde.min.js')),
  item('stackedit', 'markdown-it', 'editor', '', J('markdown-it', 'dist/markdown-it.min.js')),
  item('showdown', 'Showdown', 'editor', '', J('showdown', 'dist/showdown.min.js')),
  item('turndown', 'Turndown', 'editor', '', J('turndown', 'lib/turndown.browser.umd.js')),
  item('linkify', 'Linkify', 'js', '', J('linkifyjs', 'dist/linkify.min.js')),
  item('he', 'he (HTML entities)', 'js', '', J('he', 'he.js')),
  item('idb', 'idb', 'js', '', U('idb', 'build/umd.js')),
  item('dexie', 'Dexie', 'js', '', J('dexie', 'dist/dexie.min.js')),
  item('pdfjs', 'PDF.js', 'js', '', J('pdfjs-dist', 'build/pdf.min.mjs')),
  item('viewerjs', 'Viewer.js', 'ui', J('viewerjs', 'dist/viewer.min.css'), J('viewerjs', 'dist/viewer.min.js')),
  item('medium-zoom', 'medium-zoom', 'ui', '', J('medium-zoom', 'dist/medium-zoom.min.js')),
  item('glightbox', 'GLightbox', 'ui', J('glightbox', 'dist/css/glightbox.min.css'), J('glightbox', 'dist/js/glightbox.min.js')),
  item('lite-youtube', 'lite-youtube', 'media', '', J('@justinribeiro/lite-youtube', 'lite-youtube.js')),
  item('plyr', 'Plyr', 'media', J('plyr', 'dist/plyr.css'), J('plyr', 'dist/plyr.polyfilled.min.js')),
  item('videojs', 'Video.js', 'media', J('video.js', 'dist/video-js.min.css'), J('video.js', 'dist/video.min.js')),
  item('wavesurfer', 'WaveSurfer', 'media', '', J('wavesurfer.js', 'dist/wavesurfer.min.js')),
  item('rough', 'Rough.js', 'js', '', J('roughjs', 'bundled/rough.js')),
  item('rough-notation', 'Rough Notation', 'js', '', J('rough-notation', 'lib/rough-notation.iife.js')),
  item('canvas-confetti', 'canvas-confetti', 'js', '', J('canvas-confetti', 'dist/confetti.browser.js')),
  item('mojs', 'mo.js', 'js', '', J('@mojs/core', 'dist/mo.umd.js')),
  item('lottie-player', 'Lottie Player', 'js', '', J('@lottiefiles/lottie-player', 'dist/lottie-player.js')),
  item('autoanimate', 'AutoAnimate', 'js', '', J('@formkit/auto-animate', 'index.umd.js')),
  item('floating-ui', 'Floating UI', 'js', '', J('@floating-ui/dom', 'dist/floating-ui.dom.umd.min.js')),
  item('motion', 'Motion One', 'js', '', J('motion', 'dist/motion.js')),
  item('ztext', 'ztext.js', 'js', '', J('ztext', 'dist/ztext.min.js')),
  item('patternomaly', 'patternomaly', 'charts', '', J('patternomaly', 'dist/patternomaly.js')),
  item('chartjs-datalabels', 'Chart.js DataLabels', 'charts', '', J('chartjs-plugin-datalabels', 'dist/chartjs-plugin-datalabels.min.js')),
  item('chartjs-zoom', 'Chart.js Zoom', 'charts', '', J('chartjs-plugin-zoom', 'dist/chartjs-plugin-zoom.min.js')),
  item('date-fns', 'date-fns', 'js', '', J('date-fns', 'cdn.min.js')),
  item('chrono', 'chrono-node', 'js', '', ''),
  item('iframe-resizer', 'iframe-resizer', 'js', '', J('iframe-resizer', 'js/iframeResizer.min.js')),
  item('posthog', 'PostHog js', 'js', '', J('posthog-js', 'dist/array.full.js')),
  item('plausible', 'Plausible', 'js', '', ''),
  item('canvasjs', 'CanvasJS', 'charts', '', 'https://cdn.canvasjs.com/canvasjs.min.js'),
  item('justgage', 'JustGage', 'charts', '', J('justgage', 'dist/justgage.min.js')),
  item('gaugejs', 'Gauge.js', 'charts', '', J('gaugeJS', 'dist/gauge.min.js')),
  item('sparkline', 'jquery.sparkline', 'charts', '', J('jquery-sparkline', 'jquery.sparkline.min.js')),
  item('peity', 'Peity', 'charts', '', J('peity', 'jquery.peity.min.js')),
  item('morris', 'Morris.js', 'charts', J('morris.js06', 'morris.css'), J('morris.js06', 'morris.min.js')),
  item('flot', 'Flot', 'charts', '', J('flot', 'dist/es5/jquery.flot.js')),
  item('dygraphs', 'Dygraphs', 'charts', J('dygraphs', 'dist/dygraph.min.css'), J('dygraphs', 'dist/dygraph.min.js')),
  item('metricsgraphics', 'MetricsGraphics', 'charts', J('metrics-graphics', 'dist/metricsgraphics.css'), J('metrics-graphics', 'dist/metricsgraphics.min.js')),
  item('taucharts', 'Taucharts', 'charts', J('taucharts', 'dist/taucharts.min.css'), J('taucharts', 'dist/taucharts.min.js')),
  item('dcjs', 'dc.js', 'charts', J('dc', 'dist/style/dc.min.css'), J('dc', 'dist/dc.min.js')),
  item('crossfilter', 'Crossfilter', 'data', '', J('crossfilter2', 'crossfilter.min.js')),
  item('simple-statistics', 'simple-statistics', 'data', '', J('simple-statistics', 'dist/simple-statistics.min.js')),
  item('regression', 'regression-js', 'data', '', J('regression', 'dist/regression.min.js')),
  item('arquero', 'Arquero', 'data', '', J('arquero', 'dist/arquero.min.js')),
  item('danfo', 'Danfo.js', 'data', '', J('danfojs', 'lib/bundle.js')),
  item('mljs', 'ml.js PCA', 'data', '', J('ml-pca', 'pca.min.js')),
  item('chroma', 'chroma.js', 'js', '', J('chroma-js', 'chroma.min.js')),
  item('color', 'color', 'js', '', J('color', 'index.js')),
  item('tinycolor', 'TinyColor', 'js', '', J('@ctrl/tinycolor', 'dist/tinycolor-min.js')),
  item('pickr', 'Pickr', 'ui', J('@simonwep/pickr', 'dist/themes/nano.min.css'), J('@simonwep/pickr', 'dist/pickr.min.js')),
  item('noui', 'wNumb', 'js', '', J('wnumb', 'wNumb.min.js')),
  item('imask', 'IMask', 'ui', '', J('imask', 'dist/imask.min.js')),
  item('cleave', 'Cleave.js', 'ui', '', J('cleave.js', 'dist/cleave.min.js')),
  item('autosize', 'Autosize', 'ui', '', J('autosize', 'dist/autosize.min.js')),
  item('fitty', 'Fitty', 'js', '', J('fitty', 'dist/fitty.min.js')),
  item('textfit', 'textFit', 'js', '', J('textfit', 'textFit.min.js')),
  item('hyphenopoly', 'Hyphenopoly', 'js', '', J('hyphenopoly', 'Hyphenopoly_Loader.js')),
  item('markjs', 'mark.js', 'js', '', J('mark.js', 'dist/mark.min.js')),
  item('mark.js', 'mark.js alt', 'js', '', ''),
  item('scroll-into-view', 'scroll-into-view-if-needed', 'js', '', J('scroll-into-view-if-needed', 'umd/scroll-into-view-if-needed.min.js')),
  item('lozad', 'Lozad.js', 'js', '', J('lozad', 'dist/lozad.min.js')),
  item('lazysizes', 'lazysizes', 'js', '', J('lazysizes', 'lazysizes.min.js')),
  item('vanilla-lazyload', 'vanilla-lazyload', 'js', '', J('vanilla-lazyload', 'dist/lazyload.min.js')),
  item('imagesloaded', 'imagesLoaded', 'js', '', J('imagesloaded', 'imagesloaded.pkgd.min.js')),
  item('masonry', 'Masonry', 'ui', '', J('masonry-layout', 'dist/masonry.pkgd.min.js')),
  item('isotope', 'Isotope', 'ui', '', J('isotope-layout', 'dist/isotope.pkgd.min.js')),
  item('packery', 'Packery', 'ui', '', J('packery', 'dist/packery.pkgd.min.js')),
  item('flickity', 'Flickity', 'ui', J('flickity', 'dist/flickity.min.css'), J('flickity', 'dist/flickity.pkgd.min.js')),
  item('glider', 'Glider.js', 'ui', J('glider-js', 'glider.min.css'), J('glider-js', 'glider.min.js')),
  item('embla', 'Embla Carousel', 'ui', '', J('embla-carousel', 'embla-carousel.umd.js')),
  item('keen-slider', 'Keen Slider', 'ui', J('keen-slider', 'keen-slider.min.css'), J('keen-slider', 'keen-slider.js')),
  item('tiny-slider', 'Tiny Slider 2', 'ui', J('tiny-slider', 'dist/tiny-slider.css'), J('tiny-slider', 'dist/min/tiny-slider.js')),
  item('slick', 'Slick', 'ui', J('slick-carousel', 'slick/slick.css'), J('slick-carousel', 'slick/slick.min.js')),
  item('owl', 'Owl Carousel 2', 'ui', J('owl.carousel', 'dist/assets/owl.carousel.min.css'), J('owl.carousel', 'dist/owl.carousel.min.js')),
  item('justified-gallery', 'Justified Gallery', 'ui', J('justifiedGallery', 'dist/css/justifiedGallery.min.css'), J('justifiedGallery', 'dist/js/jquery.justifiedGallery.min.js')),
  item('lightgallery', 'lightGallery', 'ui', J('lightgallery', 'css/lightgallery-bundle.min.css'), J('lightgallery', 'lightgallery.min.js')),
  item('fancybox', 'Fancybox', 'ui', J('@fancyapps/ui', 'dist/fancybox/fancybox.css'), J('@fancyapps/ui', 'dist/fancybox/fancybox.umd.js')),
  item('baguettebox', 'baguetteBox', 'ui', J('baguettebox.js', 'dist/baguetteBox.min.css'), J('baguettebox.js', 'dist/baguetteBox.min.js')),
  item('nanogallery2', 'nanogallery2', 'ui', J('nanogallery2', 'dist/css/nanogallery2.min.css'), J('nanogallery2', 'dist/jquery.nanogallery2.min.js')),
  item('spotlight', 'Spotlight.js', 'ui', J('spotlight.js', 'dist/css/spotlight.min.css'), J('spotlight.js', 'dist/spotlight.bundle.js')),
  item('panzoom', 'Panzoom', 'ui', '', J('@panzoom/panzoom', 'dist/panzoom.min.js')),
  item('zoomist', 'Zoomist', 'ui', J('zoomist', 'zoomist.min.css'), J('zoomist', 'zoomist.min.js')),
  item('viewer', 'Viewer.js alt', 'ui', '', ''),
  item('openseadragon', 'OpenSeadragon', 'ui', '', J('openseadragon', 'build/openseadragon/openseadragon.min.js')),
  item('pdfobject', 'PDFObject', 'js', '', J('pdfobject', 'pdfobject.min.js')),
  item('printjs', 'Print.js', 'js', J('print-js', 'dist/print.css'), J('print-js', 'dist/print.js')),
  item('html2pdf', 'html2pdf.js', 'js', '', J('html2pdf.js', 'dist/html2pdf.bundle.min.js')),
  item('dom-to-image', 'dom-to-image', 'js', '', J('dom-to-image', 'dist/dom-to-image.min.js')),
  item('rasterizehtml', 'rasterizeHTML', 'js', '', J('rasterizehtml', 'dist/rasterizeHTML.min.js'))
].filter((x) => x.id && (x.css || x.js) && x.id !== 'trading-vue' && x.name !== 'deprecated skip' && x.name !== 'mark.js alt' && x.name !== 'Viewer.js alt')

export const CATALOG_WIDGETS = [
  { id: 'tv', name: 'TradingView Advanced Chart', cat: 'market', hint: 'tv:NASDAQ:AAPL' },
  { id: 'tvmini', name: 'TradingView Mini Chart', cat: 'market', hint: 'tvmini:BINANCE:BTCUSDT' },
  { id: 'tvticker', name: 'TradingView Symbol Overview', cat: 'market', hint: 'tvticker:SPX' },
  { id: 'tvtape', name: 'TradingView Ticker Tape', cat: 'market', hint: 'tvtape:NASDAQ:AAPL,NASDAQ:MSFT,BINANCE:BTCUSDT' },
  { id: 'tvta', name: 'TradingView Technical Analysis', cat: 'market', hint: 'tvta:NASDAQ:AAPL' },
  { id: 'tvheat', name: 'TradingView Stock Heatmap', cat: 'market', hint: 'tvheat' },
  { id: 'quote', name: 'Cotización Trujillo', cat: 'market', hint: 'quote:MSFT' },
  { id: 'yt', name: 'YouTube', cat: 'media', hint: 'yt:VIDEO_ID' }
]

const BY_ID = Object.fromEntries(CATALOG.map((x) => [x.id, x]))

export function catalogPublic() {
  return {
    cdns: CATALOG.map((x) => ({ id: x.id, name: x.name, cat: x.cat })),
    widgets: CATALOG_WIDGETS
  }
}

export function injectHtmlAssets(html, widgets) {
  const src = String(html || '')
  const cleaned = src.replace(/<!--ta-cdn-->[\s\S]*?<!--\/ta-cdn-->/g, '')
  const ids = []
  ;(widgets || []).forEach((w) => {
    if (w && w.type === 'cdn' && w.id && BY_ID[w.id]) ids.push(w.id)
  })
  const uniq = [...new Set(ids)]
  if (!uniq.length) return cleaned
  const tags = uniq.map((id) => {
    const it = BY_ID[id]
    let t = ''
    if (it.css) t += '<link rel="stylesheet" href="' + it.css + '">\n'
    if (it.js) t += '<script src="' + it.js + '"><\/script>\n'
    return t
  }).join('')
  const block = '<!--ta-cdn-->\n' + tags + '<!--/ta-cdn-->\n'
  if (/<\/head>/i.test(cleaned)) return cleaned.replace(/<\/head>/i, block + '</head>')
  if (/<html[\s>]/i.test(cleaned)) return cleaned.replace(/<html[^>]*>/i, (m) => m + '\n<head>\n' + block + '</head>\n')
  return '<!DOCTYPE html><html><head>\n' + block + '</head><body>\n' + cleaned + '\n</body></html>'
}

export function tradingViewSrc(kind, symbol) {
  const sym = encodeURIComponent(String(symbol || 'NASDAQ:AAPL').toUpperCase())
  if (kind === 'tvmini') {
    return 'https://s.tradingview.com/embed-widget/mini-symbol-overview/?locale=es#' + encodeURIComponent(JSON.stringify({ symbol: String(symbol || 'NASDAQ:AAPL').toUpperCase(), colorTheme: 'dark', dateRange: '12M', isTransparent: false, autosize: true }))
  }
  if (kind === 'tvticker' || kind === 'tvta') {
    const path = kind === 'tvta' ? 'technical-analysis' : 'symbol-overview'
    return 'https://s.tradingview.com/embed-widget/' + path + '/?locale=es#' + encodeURIComponent(JSON.stringify({ symbol: String(symbol || 'NASDAQ:AAPL').toUpperCase(), colorTheme: 'dark', isTransparent: false, autosize: true }))
  }
  if (kind === 'tvtape') {
    const symbols = String(symbol || 'NASDAQ:AAPL').split(',').map((s) => ({ proName: s.trim().toUpperCase(), title: s.trim().split(':').pop() }))
    return 'https://s.tradingview.com/embed-widget/ticker-tape/?locale=es#' + encodeURIComponent(JSON.stringify({ symbols, colorTheme: 'dark', isTransparent: true, displayMode: 'adaptive' }))
  }
  if (kind === 'tvheat') {
    return 'https://s.tradingview.com/embed-widget/stock-heatmap/?locale=es#' + encodeURIComponent(JSON.stringify({ colorTheme: 'dark', dataSource: 'SPX500', isTransparent: false }))
  }
  return 'https://s.tradingview.com/widgetembed/?symbol=' + sym + '&interval=D&hidesidetoolbar=1&symboledit=1&saveimage=1&toolbarbg=0f172a&theme=dark&style=1&timezone=Etc/UTC&hideideas=1&locale=es&withdateranges=1'
}
